SistemaCadastro/Controllers/AlterarSenhaController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaCadastro.Helper;
using SistemaCadastro.Models;
using SistemaCadastro.Repositorio;

namespace SistemaCadastro.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;

        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
                    alterarSenhaModel.Id = usuarioLogado.Id;

                    _usuarioRepositorio.AlterarSenha(alterarSenhaModel);
                    
                    TempData["MensagemSucesso"] = $"Senha alterada com sucesso.";

                    return View("Index", alterarSenhaModel);
                }

                return View("Index",alterarSenhaModel);
            }
            catch(Exception e)
            {
                TempData["MensagemErro"] = $"Ops, erro ao alterar senha, detalhe do erro: {e.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

SistemaCadastro/Views/AlterarSenha/Index.cshtml
@model AlterarSenhaModel
@using SistemaCadastro.Enums;
@{
    ViewData["Title"] = "Alterar senha do Usúario";
}

<div class="text-center">

    <br />

    <h1 class="display-4">alterar senha do usúario</h1>
</div>

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-labe="Close">x</button>
        @TempData["MensagemErro"]
    </div>
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-labe="Close">x</button>
        @TempData["MensagemSucesso"]
    </div>
}

<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">

   
    <div class="form-group mb-3">
        <label for="SenhaAtual" class="form-label">Senha Atual</label>
        <input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite a senha atual do usúario">
        @Html.ValidationMessageFor(x => x.SenhaAtual)
    </div>

    <div class="form-group mb-3">
        <label for="NovaSenha" class="form-label">Nova Senha</label>
        <input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite a nova senha do usúario">
        @Html.ValidationMessageFor(x => x.NovaSenha)
    </div>

    <div class="form-group mb-3">
        <label for="ConfirmarNovaSenha" class="form-label">Confirmar Nova Senha</label>
        <input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Digite a confirmação da nova senha do usúario">
        @Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Home" asp-action="Index" role="button">Voltar</a>
</form>